// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBjL14nlRRtwlkSC16czRGjLjWZL3oPGo',
    appId: '1:813024926738:web:e86dda2440b10e0b574ccb',
    messagingSenderId: '813024926738',
    projectId: 'mini-game-f9f74',
    authDomain: 'mini-game-f9f74.firebaseapp.com',
    storageBucket: 'mini-game-f9f74.appspot.com',
    measurementId: 'G-JB4TWJSDWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaerfbP_4dpkkwJslXUY7qiez8oCROMhM',
    appId: '1:813024926738:android:d3dd6df4c6da234d574ccb',
    messagingSenderId: '813024926738',
    projectId: 'mini-game-f9f74',
    storageBucket: 'mini-game-f9f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_XP3YpoSie3GMOwTSxbNCTXULuXBpDvI',
    appId: '1:813024926738:ios:f16990fc4ee49849574ccb',
    messagingSenderId: '813024926738',
    projectId: 'mini-game-f9f74',
    storageBucket: 'mini-game-f9f74.appspot.com',
    iosBundleId: 'com.example.miniApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_XP3YpoSie3GMOwTSxbNCTXULuXBpDvI',
    appId: '1:813024926738:ios:326afad2fbbf6278574ccb',
    messagingSenderId: '813024926738',
    projectId: 'mini-game-f9f74',
    storageBucket: 'mini-game-f9f74.appspot.com',
    iosBundleId: 'com.example.miniApp.RunnerTests',
  );
}
